### ISSUE TITLE
How to add the gif preview manually on a template?

### ISSUE THREAD

**Issue by vanduzled** [SubZtep/gif-animation-preview#2]
Hi

I'm inserting a gif thru a template but the gif player won't appear. It will only appear when you insert the gif on the wordpress editor.

I tried inserting "-gap" class on the image with no success.

**Comment by SubZtep** [comment]
Hi

Only images in posts are supported because the plugin generate preview image on the fly.

Anyway with the current version you can do it, your image tag must match to this css query:
https://github.com/SubZtep/gif-animation-preview/blob/master/gapplayer.js#L200

You need to generate a preview image manually and name it `FILENAME-gap.jpg` and put it next to the gif image in the same directory.

Here is an example html snippet:
`<img src="http://localhost/giphy-gap.jpg" data-gif="http://localhost/giphy.gif" />`

This method will not work with future release.

**Comment by vanduzled** [comment]
I see. 

Tried and works fine. Can't wait for the future release.

thanks!
